version: '3.1'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "prathmesH@99"
    volumes:
      - ./dbData:/var/lib/postgresql/data
